try locking versions to track down:
generating indices... genindex py-modindex done
highlighting module code... [100%] grill.write

Traceback (most recent call last):
  File "/home/docs/checkouts/readthedocs.org/user_builds/grill/envs/feature-docs_examples/lib/python3.7/site-packages/sphinx/builders/html/__init__.py", line 1044, in handle_page
    output = self.templates.render(templatename, ctx)
  File "/home/docs/checkouts/readthedocs.org/user_builds/grill/envs/feature-docs_examples/lib/python3.7/site-packages/readthedocs_ext/readthedocs.py", line 185, in rtd_render
    content = old_render(template, render_context)
  File "/home/docs/checkouts/readthedocs.org/user_builds/grill/envs/feature-docs_examples/lib/python3.7/site-packages/sphinx/jinja2glue.py", line 196, in render
    return self.environment.get_template(template).render(context)
  File "/home/docs/checkouts/readthedocs.org/user_builds/grill/envs/feature-docs_examples/lib/python3.7/site-packages/jinja2/environment.py", line 1304, in render
    self.environment.handle_exception()
  File "/home/docs/checkouts/readthedocs.org/user_builds/grill/envs/feature-docs_examples/lib/python3.7/site-packages/jinja2/environment.py", line 925, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/home/docs/checkouts/readthedocs.org/user_builds/grill/envs/feature-docs_examples/lib/python3.7/site-packages/sphinx_typlog_theme/page.html", line 21, in top-level template code
    <meta property="og:image" content="{{ src }}">
  File "/home/docs/checkouts/readthedocs.org/user_builds/grill/envs/feature-docs_examples/lib/python3.7/site-packages/sphinx_typlog_theme/layout.html", line 69, in top-level template code
    {%- block extrahead %}{% endblock %}
  File "/home/docs/checkouts/readthedocs.org/user_builds/grill/envs/feature-docs_examples/lib/python3.7/site-packages/sphinx_typlog_theme/page.html", line 30, in block 'extrahead'
    {%- if theme_description and 'name="description"' not in metatags %}
jinja2.exceptions.UndefinedError: 'metatags' is undefined

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/docs/checkouts/readthedocs.org/user_builds/grill/envs/feature-docs_examples/lib/python3.7/site-packages/sphinx/cmd/build.py", line 280, in build_main
    app.build(args.force_all, filenames)
  File "/home/docs/checkouts/readthedocs.org/user_builds/grill/envs/feature-docs_examples/lib/python3.7/site-packages/sphinx/application.py", line 350, in build
    self.builder.build_update()
  File "/home/docs/checkouts/readthedocs.org/user_builds/grill/envs/feature-docs_examples/lib/python3.7/site-packages/sphinx/builders/__init__.py", line 294, in build_update
    len(to_build))
  File "/home/docs/checkouts/readthedocs.org/user_builds/grill/envs/feature-docs_examples/lib/python3.7/site-packages/sphinx/builders/__init__.py", line 359, in build
    self.finish()
  File "/home/docs/checkouts/readthedocs.org/user_builds/grill/envs/feature-docs_examples/lib/python3.7/site-packages/sphinx/builders/html/__init__.py", line 632, in finish
    self.finish_tasks.add_task(self.gen_pages_from_extensions)
  File "/home/docs/checkouts/readthedocs.org/user_builds/grill/envs/feature-docs_examples/lib/python3.7/site-packages/sphinx/util/parallel.py", line 49, in add_task
    res = task_func()
  File "/home/docs/checkouts/readthedocs.org/user_builds/grill/envs/feature-docs_examples/lib/python3.7/site-packages/sphinx/builders/html/__init__.py", line 656, in gen_pages_from_extensions
    self.handle_page(pagename, context, template)
  File "/home/docs/checkouts/readthedocs.org/user_builds/grill/envs/feature-docs_examples/lib/python3.7/site-packages/sphinx/builders/html/__init__.py", line 1052, in handle_page
    (pagename, exc)) from exc
sphinx.errors.ThemeError: An error happened in rendering the page _modules/grill/write.
Reason: UndefinedError("'metatags' is undefined")